server:
  port: 4003

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/web_practice?currentSchema=auth_db
    username: postgres
    password: root
    hikari:
      maximum-pool-size: 20

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

jwt:
  token:
    lifetime: 1440
    secret: "5eVD42Bj8rw9Rl4F${F$"