server:
  port: 4002

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  thymeleaf:
    prefix: file:./staticresource/templates/
    cache: false
  web:
    resources:
      static-locations: file:./staticresource/
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/web_practice?currentSchema=problems_db
    username: postgres
    password: root
    hikari:
      maximum-pool-size: 20