spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/aisd
    username: postgres
    password: root
    hikari:
      maximum-pool-size: 20

  thymeleaf:
    prefix: file:./static/templates/
    cache: false

  web:
    resources:
      static-locations: file:./static/
